apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tesladash
  labels:
    app: tesladash
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: tesladash.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tesladash
                port:
                  number: 80
  tls:
    - hosts:
        - tesladash.example.com
      secretName: tesladash-tls
