apiVersion: v1
kind: Service
metadata:
  name: tesladash
  labels:
    app: tesladash
spec:
  type: ClusterIP
  selector:
    app: tesladash
  ports:
    - name: http
      port: 80
      targetPort: 80
