apiVersion: v2
name: tesladash
description: TeslaDash â€” Fullscreen Tesla Browser portal

# Helm chart type
# application: Deploys a service into the cluster
# library: Only includes templates users can use to build their own charts

type: application
version: 
appVersion: ""